services:
  playground-docsify:
    container_name: 'docsify'
    hostname: 'docsify'
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: '/docs'
    tty: true
    volumes:
      - type: bind
        source: ../docs
        target: /docs