services:
  playground-typescript:
    container_name: 'playground-typescript'
    hostname: 'typescript'
    build: 
      context: .
      dockerfile: Dockerfile
      # args:
      #   USERNAME: $USERNAME_
      #   UID: $UID
      #   GID: $GID
    restart: always
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace