# Node.js & Typescript Development Container Images By Microsoft
# https://hub.docker.com/_/microsoft-devcontainers-typescript-node
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

USER node
WORKDIR /docs
# RUN npm install -g ts-node
RUN npm install -g docsify-cli