# Node.js & Typescript Development Container Images By Microsoft
# https://hub.docker.com/_/microsoft-devcontainers-typescript-node
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

RUN npm install --save ts-node

USER node
WORKDIR /workspace